// <autogenerated /> because this is copy of Selectable editor
#if UNITY_EDITOR
namespace UIWidgets
{
	using UnityEditor;
	using UnityEditor.AnimatedValues;
	using UnityEditor.Animations;
	using UnityEngine;
	using UnityEngine.Events;
	using UnityEngine.UI;

	/// <summary>
	/// SelectableHelperList editor.
	/// </summary>
	[CustomEditor(typeof(SelectableHelperList), true)]
	public class SelectableHelperListEditor : UIWidgetsMonoEditor
	{
		SerializedProperty m_Script;
		SerializedProperty targetGraphics;
		SerializedProperty m_TransitionProperty;
		SerializedProperty m_ColorBlockProperty;
		SerializedProperty m_SpriteStateProperty;
		SerializedProperty m_AnimTriggerProperty;

		AnimBool m_ShowColorTint = new AnimBool();
		AnimBool m_ShowSpriteTrasition = new AnimBool();
		AnimBool m_ShowAnimTransition = new AnimBool();

		string[] m_PropertyPathToExcludeForChildClasses;

		UnityAction repaintDelegate;

		UnityAction RepaintDelegate
		{
			get
			{
				if (repaintDelegate == null)
				{
					repaintDelegate = Repaint;
				}

				return repaintDelegate;
			}
		}

		/// <summary>
		/// Init.
		/// </summary>
		protected virtual void OnEnable()
		{
			m_Script = serializedObject.FindProperty("m_Script");
			targetGraphics = serializedObject.FindProperty("targetGraphics");
			m_TransitionProperty = serializedObject.FindProperty("transition");
			m_ColorBlockProperty = serializedObject.FindProperty("colors");
			m_SpriteStateProperty = serializedObject.FindProperty("spriteState");
			m_AnimTriggerProperty = serializedObject.FindProperty("animationTriggers");

			m_PropertyPathToExcludeForChildClasses = new[] {
				m_Script.propertyPath,
				m_TransitionProperty.propertyPath,
				m_ColorBlockProperty.propertyPath,
				m_SpriteStateProperty.propertyPath,
				m_AnimTriggerProperty.propertyPath,
				targetGraphics.propertyPath,
			};

			var trans = GetTransition(m_TransitionProperty);
			m_ShowColorTint.value = (trans == Selectable.Transition.ColorTint);
			m_ShowSpriteTrasition.value = (trans == Selectable.Transition.SpriteSwap);
			m_ShowAnimTransition.value = (trans == Selectable.Transition.Animation);

			m_ShowColorTint.valueChanged.AddListener(RepaintDelegate);
			m_ShowSpriteTrasition.valueChanged.AddListener(RepaintDelegate);
		}

		/// <summary>
		/// Disable.
		/// </summary>
		protected virtual void OnDisable()
		{
			m_ShowColorTint.valueChanged.RemoveListener(RepaintDelegate);
			m_ShowSpriteTrasition.valueChanged.RemoveListener(RepaintDelegate);
		}

		static Selectable.Transition GetTransition(SerializedProperty transition)
		{
			return (Selectable.Transition)transition.enumValueIndex;
		}

		/// <summary>
		/// Draw inspector GUI.
		/// </summary>
		public override void OnInspectorGUI()
		{
			ValidateTargets();

			serializedObject.Update();

			var shl = target as SelectableHelperList;

			if (!IsDerivedSelectableHelperListEditor())
			{
				EditorGUILayout.PropertyField(m_Script);
			}

			var trans = GetTransition(m_TransitionProperty);

			var animator = shl.GetComponent<Animator>();
			m_ShowColorTint.target = (!m_TransitionProperty.hasMultipleDifferentValues && trans == Button.Transition.ColorTint);
			m_ShowSpriteTrasition.target = (!m_TransitionProperty.hasMultipleDifferentValues && trans == Button.Transition.SpriteSwap);
			m_ShowAnimTransition.target = (!m_TransitionProperty.hasMultipleDifferentValues && trans == Button.Transition.Animation);

			EditorGUILayout.PropertyField(m_TransitionProperty);

			++EditorGUI.indentLevel;
			{
				if (trans == Selectable.Transition.ColorTint || trans == Selectable.Transition.SpriteSwap)
				{
					EditorGUILayout.PropertyField(targetGraphics);
				}

				if (EditorGUILayout.BeginFadeGroup(m_ShowColorTint.faded))
				{
					EditorGUILayout.PropertyField(m_ColorBlockProperty);
					EditorGUILayout.Space();
				}
				EditorGUILayout.EndFadeGroup();

				if (EditorGUILayout.BeginFadeGroup(m_ShowSpriteTrasition.faded))
				{
					EditorGUILayout.PropertyField(m_SpriteStateProperty);
					EditorGUILayout.Space();
				}
				EditorGUILayout.EndFadeGroup();

				if (EditorGUILayout.BeginFadeGroup(m_ShowAnimTransition.faded))
				{
					EditorGUILayout.PropertyField(m_AnimTriggerProperty);

					if (animator == null || animator.runtimeAnimatorController == null)
					{
						Rect buttonRect = EditorGUILayout.GetControlRect();
						buttonRect.xMin += EditorGUIUtility.labelWidth;
						if (GUI.Button(buttonRect, "Auto Generate Animation", EditorStyles.miniButton))
						{
							var controller = GenerateSelectableAnimatorContoller(shl.AnimationTriggers, shl);
							if (controller != null)
							{
								if (animator == null)
								{
									animator = shl.gameObject.AddComponent<Animator>();
								}

								AnimatorController.SetAnimatorController(animator, controller);
							}
						}
					}
				}
				EditorGUILayout.EndFadeGroup();
			}
			--EditorGUI.indentLevel;

			EditorGUILayout.Space();

			EditorGUI.BeginChangeCheck();
			Rect toggleRect = EditorGUILayout.GetControlRect();
			toggleRect.xMin += EditorGUIUtility.labelWidth;

			ChildClassPropertiesGUI();

			UtilitiesEditor.ApplyModifiedProperties(serializedObject);

			ValidateTargets();
		}

		void ChildClassPropertiesGUI()
		{
			if (IsDerivedSelectableHelperListEditor())
			{
				return;
			}

			DrawPropertiesExcluding(serializedObject, m_PropertyPathToExcludeForChildClasses);
		}

		bool IsDerivedSelectableHelperListEditor()
		{
			return GetType() != typeof(SelectableHelperListEditor);
		}

		static AnimatorController GenerateSelectableAnimatorContoller(AnimationTriggers animationTriggers, SelectableHelperList target)
		{
			if (target == null)
			{
				return null;
			}

			var path = GetSaveControllerPath(target);
			if (string.IsNullOrEmpty(path))
			{
				return null;
			}

			var normalName = string.IsNullOrEmpty(animationTriggers.normalTrigger) ? "Normal" : animationTriggers.normalTrigger;
			var highlightedName = string.IsNullOrEmpty(animationTriggers.highlightedTrigger) ? "Highlighted" : animationTriggers.highlightedTrigger;
			var pressedName = string.IsNullOrEmpty(animationTriggers.pressedTrigger) ? "Pressed" : animationTriggers.pressedTrigger;
			var disabledName = string.IsNullOrEmpty(animationTriggers.disabledTrigger) ? "Disabled" : animationTriggers.disabledTrigger;

			var controller = AnimatorController.CreateAnimatorControllerAtPath(path);

			GenerateTriggerableTransition(normalName, controller);
			GenerateTriggerableTransition(highlightedName, controller);
			GenerateTriggerableTransition(pressedName, controller);
			GenerateTriggerableTransition(disabledName, controller);

			return controller;
		}

		static string GetSaveControllerPath(SelectableHelperList target)
		{
			var defaultName = target.gameObject.name;
			var message = string.Format("Create a new animator for the game object '{0}':", defaultName);

			return EditorUtility.SaveFilePanelInProject("New Animation Controller", defaultName, "controller", message);
		}

		static AnimationClip GenerateTriggerableTransition(string name, AnimatorController controller)
		{
			var clip = AnimatorController.AllocateAnimatorClip(name);
			AssetDatabase.AddObjectToAsset(clip, controller);

			var state = controller.AddMotion(clip);

			controller.AddParameter(name, UnityEngine.AnimatorControllerParameterType.Trigger);

			var stateMachine = controller.layers[0].stateMachine;
			var transition = stateMachine.AddAnyStateTransition(state);
			transition.AddCondition(UnityEditor.Animations.AnimatorConditionMode.If, 0, name);

			return clip;
		}
	}
}
#endif